import React from "react";

interface FooterBrandingProps {
  auditDate?: string;
  url?: string;
}

export const FooterBranding: React.FC<FooterBrandingProps> = ({
  auditDate,
  url,
}) => {
  return (
    <div
      style={{
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        height: 100,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "0 60px",
        borderTop: "1px solid rgba(255, 255, 255, 0.06)",
        background: "rgba(0, 0, 0, 0.25)",
        backdropFilter: "blur(8px)",
        WebkitBackdropFilter: "blur(8px)",
      }}
    >
      {/* Left: brand */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 10,
        }}
      >
        <div
          style={{
            width: 32,
            height: 32,
            borderRadius: 8,
            background: "linear-gradient(135deg, #7730ed, #d0bcff)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontSize: 14,
            fontWeight: 900,
            color: "#fff",
            fontFamily: "sans-serif",
          }}
        >
          O
        </div>
        <div>
          <div
            style={{
              fontSize: 14,
              fontWeight: 800,
              color: "#d0bcff",
              fontFamily: "sans-serif",
              letterSpacing: "0.04em",
            }}
          >
            ODITO AI
          </div>
          <div
            style={{
              fontSize: 10,
              color: "rgba(255,255,255,0.3)",
              fontFamily: "monospace, sans-serif",
              textTransform: "uppercase",
              letterSpacing: "0.1em",
            }}
          >
            Enterprise Audit Suite
          </div>
        </div>
      </div>

      {/* Center: engine attribution */}
      <div
        style={{
          textAlign: "center",
          fontSize: 11,
          color: "rgba(255,255,255,0.25)",
          fontFamily: "monospace, sans-serif",
          letterSpacing: "0.08em",
        }}
      >
        Generated by Odito AI Engine v3 · AI Visibility & SEO Analysis
      </div>

      {/* Right: date + confidential */}
      <div
        style={{
          textAlign: "right",
          display: "flex",
          flexDirection: "column",
          gap: 3,
        }}
      >
        {url && (
          <div
            style={{
              fontSize: 12,
              color: "rgba(255,255,255,0.4)",
              fontFamily: "monospace, sans-serif",
            }}
          >
            {url}
          </div>
        )}
        {auditDate && (
          <div
            style={{
              fontSize: 11,
              color: "rgba(255,255,255,0.25)",
              fontFamily: "monospace, sans-serif",
              textTransform: "uppercase",
              letterSpacing: "0.08em",
            }}
          >
            {auditDate} · Confidential
          </div>
        )}
      </div>
    </div>
  );
};
